In [3]:
#Dependancies and Setup
import pandas as pd

#File to load
file_to_load ='GDPdata.csv'

#Read GDP csv file into Pandas dataframe
gdp_data= pd.read_csv(file_to_load)
gdp_data.head()

,REF_DATE,GEO,DGUID,Seasonal adjustment,Prices,North American Industry Classification System (NAICS),UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1997-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Chained (2012) dollars,All industries [T001],Dollars,81,millions,6,v1000000673,1.1.1.1,1151000.0,NaN,NaN,NaN,0
1,1997-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Chained (2012) dollars,Goods-producing industries [T002],Dollars,81,millions,6,v1000000674,1.1.1.2,393954.0,NaN,NaN,NaN,0
2,1997-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Chained (2012) dollars,Service-producing industries [T003],Dollars,81,millions,6,v1000000675,1.1.1.3,756380.0,NaN,NaN,NaN,0
3,1997-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Chained (2012) dollars,Business sector industries [T004],Dollars,81,millions,6,v1000000676,1.1.1.4,NaN,..,NaN,NaN,0
4,1997-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Chained (2012) dollars,"Business sector, goods [T005]",Dollars,81,millions,6,v1000000677,1.1.1.5,NaN,..,NaN,NaN,0